php artisan elastic:create-index "App\Models\SearchIndexConfig\ProductDescriptionIndexConfigurator"
php artisan elastic:create-index "App\Models\SearchIndexConfig\BusinessDescriptionIndexConfigurator"
php artisan elastic:create-index "App\Models\SearchIndexConfig\ProductIndexConfigurator"
php artisan elastic:create-index "App\Models\SearchIndexConfig\BusinessIndexConfigurator"
php artisan scout:import "App\Models\BusinessDescription"
php artisan scout:import "App\Models\ProductDescription"
php artisan scout:import "App\Models\Business"
php artisan scout:import "App\Models\Product"